### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'

### ISSUE THREAD

**Issue by ucsky** [thoughtworksarts/EmoPy#44]
Hello,

Trying to install it on Ubuntu Bionic LTS 18 I got the following error when running the unit test:

`Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/mnt/host/sf_bob/Documents/test/EmoPy-github-master/EmoPy/__init__.py", line 1, in <module>
    from .src.fermodel import FERModel
  File "/mnt/host/sf_bob/Documents/test/EmoPy-github-master/EmoPy/src/fermodel.py", line 1, in <module>
    from keras.models import load_model
  File "/home/bob/Envs/emopy-github-master/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/bob/Envs/emopy-github-master/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/bob/Envs/emopy-github-master/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/bob/Envs/emopy-github-master/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/bob/Envs/emopy-github-master/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/bob/Envs/emopy-github-master/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 54, in <module>
    get_graph = tf_keras_backend.get_graph
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'`

**Comment by ucsky** [comment]
I edited `setup.py`: setting `keras==2.2.4` and `tensorflow==1.13.1` and now all tests pass and examples runs.

**Comment by megangoodling** [comment]
Hi @ucsky ! I tried editing my setup.py files to the versions you suggest and am still getting the same error for keras. I was wondering if there was anything else you did for this fix? Did you have to re-install anything else? Appreciate your help on this.

**Comment by alanTorresAlv** [comment]
hello, which setup.by had you edited?? I have the same issue

**Comment by farhanc4kra** [comment]
just replacing
from **keras import backend**
with:
**from tensorflow.keras import backend**

**Comment by Raikori** [comment]
where is the setup.py?

**Comment by ucsky** [comment]
Hi, this `setup.py`  here [https://github.com/thoughtworksarts/EmoPy/blob/master/setup.py](https://github.com/thoughtworksarts/EmoPy/blob/master/setup.py)
